services:
  catalog:
    image: postgres
  basketdb:
    image: postgres
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogApi/Dockerfile

volumes :
  postgres_catalog:

    
