global using Ordering.Domain.Abstraction;
global using Ordering.Domain.Enums;
global using Ordering.Domain.ValudObjects;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Ordering.Domain.Exceptions;
